languageCode = "en-us"
DefaultContentLanguage = "en"
baseURL = "/"

title = "Metricio - Dashboards for teams built with React and Node"
theme = "docdock"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/metricio/metricio-docs/blob/master/content/"

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i>&nbsp;&nbsp;View on Github"
identifier = "gh"
url = "https://github.com/metricio/metricio"
weight = 10
